### PR TITLE
Styling fixes for docs navigation tree

### PR DESCRIPTION
**Pull request by anne-usmedia**
- Doc nav styling fixes
- Tree styling fixes
- Added 600 weight font
- Breadcrumb styling improvement
- Prev & Next styling improvement

For https://linear.app/usmedia/issue/CUE-160

### CODE REVIEW

**Review by JorindeUsMedia — APPROVED** [review]

**Review by Lyoness — APPROVED** [review]
Importing to Gerrit

**Comment by Lyoness** [comment]
https://review.gerrithub.io/c/cue-lang/cuelang.org/+/550646

**Comment by Lyoness** [comment]
@anne-usmedia please rebase this PR to resolve merge conflicts

**Comment by anne-usmedia** [comment]
@Lyoness done

**Comment by myitcv** [comment]
Reimporting. Thanks for the rebase.

**Comment by Lyoness** [comment]
Closes [1992dcf](https://github.com/cue-lang/cuelang.org/commit/1992dcfb2f5c94565cb0cb9c9736599fb8b806b2) as merged.

**Pull request closed without merging**
