### PR TITLE
Editor: Setup editor in alpha website

### PR DESCRIPTION
**Pull request by JorindeUsMedia**
- Copied playground from master branch + renamed to Editor to make it future-proof
- Update all packages in package.json. Add missing packages which are needed for development or building (webpack).
- Update existing react code to use React 18.
- Remove bootstrap
- Add custom styles via scss. Custom styles will use a prefix 'cue-' to avoid conflicts with main website styles when used embeded in play page.
- Add React Dropdown component to replace old Boostrap Dropdown
- Make webpack build & bundle all js, copy wasm & static, build scss to css.
- Improve development by adding some more tasks to package.json and adding development modus to webpack so we can make webpack both build prod & dev versions and also serve the react app in the browser, make use of sourcemaps etc.
- Code style: Make sure single quotes are just everywhere and not a mix of single & double
- Add a task to copy the files needed for the website playground to the website static folder
- Implement playground on playpage on the Hugo website.
- Overrule some editor styles on the website play page to fit the sticking out logo header

Test url: https://deploy-preview-301--cue.netlify.app/play/

### CODE REVIEW

**Comment by JorindeUsMedia** [comment]
I haven't found a way yet to also build the main.wasm file using webpack so Go is still needed. I was in doubt on adding to main.wasm to gitignore. I now did that but in order to run the editor react app Go is still required to compile the wasm file. I could commit the main.wasm file as well but that means every time something changes to the wasm this file needs gets updated. But it would be easier for people to work on the react app without touching the webassembly part. Any thought on this @usm-joost or @myitcv ?

**Comment by usm-joost** [comment]
Regarding the commiting of the current main wasm file - I would say yes commit it for now (assuming it end up in the static folder). As you want the play-page to simply work at deployment.

In the next iteration for this - I can imagine having different files per cue version - so something to take into account in the future.

**Comment by usm-joost** [comment]
Also be sure to test if current play/share url's work!

**Comment by JorindeUsMedia** [comment]
I've also commited the main.wasm file + made some updates to the readme so it's now also possible to work on the editor react app without needing to have GO installed. You only need it to work on the webassembly side, but not to work on react & styles.

I've noticed an issue with the main.wasm file path within the playground on the website. I will have a look at that

**Comment by JorindeUsMedia** [comment]
I've now fixed that by changing the wasm path for each environment: react app & hugo site by setting it on a custom envObject on the document.

Share works: https://deploy-preview-301--cue.netlify.app/play/?id=1ywOiG4s_O0#cue@export@cue

**Comment by myitcv** [comment]
> Todo discussed in meeting:
> 
> * Remove footer on playground page

Specifically, we need to make this a single page app with the only scrolling happening within the two editor panes.

**Comment by JorindeUsMedia** [comment]
@myitcv I've hidden the footer and made sure the page is always filling the screen (header + playground). http://localhost:1313/play/#cue@export@cue

**Review by myitcv — APPROVED** [review]
@JorindeUsMedia - thanks for doing this. All LGTM.

@Lyoness has just closed #306 as merged. 

You should now be able to rebase against https://github.com/cue-lang/cuelang.org/commit/033e4a625bd788cb0fc108524b973afd3a0337d7

**Comment by myitcv** [comment]
Interestingly the most recent deploy failed: https://app.netlify.com/sites/cue/deploys/63fe0e7d69b153000788a83f

I could have sworn that I actually looked at the deploy earlier... perhaps you pushed another change?

**Comment by JorindeUsMedia** [comment]
@myitcv Rebased & fixed the conflicts.

**Review by myitcv — APPROVED** [review]
LGTM - the output selector appears to be a bit broken but I'll follow up on that in a separate Linear issue.

**Comment by myitcv** [comment]
Importing into GerritHub now.

**Pull request closed without merging**
