### PR TITLE
Hugo: close dropdowns on escape key

### PR DESCRIPTION
**Pull request by anne-usmedia**
- add eventlistener for escape key in dropdowns

For https://linear.app/usmedia/issue/CUE-322

### CODE REVIEW

**Review by JorindeUsMedia — APPROVED** [review]

**Comment by ErikHendrikson** [comment]
Approved.

Extra note:
public close(trigger: HTMLElement, target: HTMLElement) {
        this.isOpen = false;
        const input: HTMLInputElement = this.getInput(target);

        requestAnimationFrame(() => {
            target.classList.remove('is-open');
            trigger.classList.remove('is-active');
            // create custom event for closing autocomplete panel?

            requestAnimationFrame(() => {
                window.setTimeout(() => {
                    target.classList.remove('is-active');
                }, 400);
                input.value = '';
            });
        });
    }
    
    Whenever I press escape in the browser it errors on input being null (input.value). It's in the menu.ts (widgets) on 111. Should be a null checking.

**Comment by jpluscplusm** [comment]
@JorindeUsMedia Please could you re-review after the recent force push?

**Review by JorindeUsMedia — APPROVED** [review]

**Review by jpluscplusm — APPROVED** [review]
Tested the functional delta between this PR and alpha on the "share page to socials" popup, and it works as expected 👍 . Importing now.

**Comment by jpluscplusm** [comment]
Imported as https://review.gerrithub.io/c/cue-lang/cuelang.org/+/1172307

**Comment by jpluscplusm** [comment]
Closed via 7efea6b38c7e9f1afe0ba996cdbc8b86bb29fe94

**Pull request closed without merging**
