### PR TITLE
Hugo: accessibility improvements

### PR DESCRIPTION
**Pull request by anne-usmedia**
- Video: focus state more visible
- Video: added aria label to play button
- Tabs: only focus on tabs when there are more than one (1)

Testing:
- for video (/examples/shortcodes/youtube/): with the TAB key, navigate to a video. The animation should be more notable.
- for (code) tabs (/examples/shortcodes/code-tabs/): with the TAB key, navigate through the code tabs. The only tabs that "light up" should be the ones with more than one tab.

For https://linear.app/usmedia/issue/CUE-324

### CODE REVIEW

**Review by JorindeUsMedia — APPROVED** [review]

**Comment by jpluscplusm** [comment]
@anne-usmedia for some reason the most recent change doesn't appear to have been deployed by the Netlify bot. Please could you make some trivial whitespace/etc change to your commit message, then force push again? Hopefully the bot will then do its job correctly ... :-)

**Comment by anne-usmedia** [comment]
@jpluscplusm done!

**Review by myitcv — APPROVED** [review]
LGTM; imported as https://review.gerrithub.io/c/cue-lang/cuelang.org/+/1172541

**Comment by jpluscplusm** [comment]
Closed via e3159ff128fb76b2f7629108c46be541987ba691

**Pull request closed without merging**
