### PR TITLE
hugo/playground: Layout redesign

### PR DESCRIPTION
**Pull request by JorindeUsMedia**
- Don't show header on playground page
- Center loading spinner for playground page
- Remove old css for hugo/playground page
- Remove scrolling/pagination for tabs on smaller screens for now because we don't use it and it conflicts with the dropdown. If it's need in the future I've proposed a different sollution: https://linear.app/usmedia/issue/CUE-265
- Add code language dropdowns on tabs itself
- If 1 item in tab lang options show tabs text, if multiple show tab dropdown
- Setup workspace models & config. For now used in workspace dropdown but when we're going to implement it will be just in more places.
- Add new icons to spritesheet
- New header html & styling
- Menu component + styling
- Nav component + styling
- Mobile header (icon version for some buttons)
- Workspace dropdown
- Move input, output, function to Workspace dropdown
- Examples dropdown (content to come in separate story)
- Share button redesign
- On mobile toggle showing url when clicking on share button & is saved

For https://linear.app/usmedia/issue/CUE-249

### CODE REVIEW

**Comment by JorindeUsMedia** [comment]
Feedback Joost:

- Share: Switch around copy button and input so you can easily click on copy without moving the mouse
- Share: On mobile also show text 'Copy" and smaller input because copy is more important than the input there

**Comment by myitcv** [comment]
Looks good as a first start. 

We also need to consider https://github.com/cue-lang/cue/issues/2440 (which is effectively https://linear.app/usmedia/issue/CUE-280) at some point too.

**Comment by myitcv** [comment]
Also, I checked that the new playground continues to load existing examples:

https://deploy-preview-385--cue.netlify.app/play?id=uSN2s_FLARf#cue@export@cue

compares perfectly with:

https://cuelang.org/play?id=uSN2s_FLARf#cue@export@cue

**Comment by myitcv** [comment]
One thing I have not yet checked is whether the functions, inputs/outputs etc work as expected.

**Comment by myitcv** [comment]
@JorindeUsMedia - please ping here when you want this merged. 

Totally understand that having separate PRs stacked on top of each other is painful!

**Comment by JorindeUsMedia** [comment]
@myitcv I've processed Peter's feedback so it's ready to be merged now

**Comment by myitcv** [comment]
Importing this now.

**Comment by myitcv** [comment]
Imported as https://review.gerrithub.io/c/cue-lang/cuelang.org/+/1167473

**Review by myitcv — APPROVED** [review]
LGTM

**Comment by myitcv** [comment]
Closed via 80c173ddfb6d715125a37b2b703e01b4a4355753

**Pull request closed without merging**
