### PR TITLE
Change logo hover from inner to outer circle

### PR DESCRIPTION
**Pull request by anne-usmedia**
Change logo hover from inner to outer circle. For testing go to any page on localhost:1313

### CODE REVIEW

**Comment by myitcv** [comment]
Manually approved the preview in Netlify. I've also made a settings change that should mean that subsequent force-pushes to this PR will automatically trigger a preview.

@anne-usmedia - nice to meet you via this PR! Please can you try another force push to test whether the Netlify change has worked? If it has worked, then a force push from you should automatically trigger a preview in Netlify.

Thanks and have a great weekend.

**Comment by anne-usmedia** [comment]
Hi @myitcv, nice to meet you too! I did another force push, and it seems to have worked

**Comment by myitcv** [comment]
> Hi @myitcv, nice to meet you too! I did another force push, and it seems to have worked

Fantastic!

**Comment by myitcv** [comment]
@Lyoness - please review.

**Review by Lyoness — APPROVED** [review]

**Comment by Lyoness** [comment]
@anne-usmedia approved.  Also nice to meet you!  Welcome to CUE.

**Review by Lyoness — CHANGES_REQUESTED** [review]
@anne-usmedia: please can you ensure the commit message reflects the description in the PR above? That way, our git history can be read entirely from git log, rather than having to click through to a PR.

**Comment by anne-usmedia** [comment]
@Lyoness nice to meet you too!

I'm not used to working with Github so please tell me if I'm wrong, but I thought the commit message was the same except for the "For testing go to any page on localhost:1313" part. Or do you need that to be in the commit message as well?

**Review by myitcv — APPROVED** [review]
LGTM.

**Review by Lyoness — APPROVED** [review]

**Comment by myitcv** [comment]
This PR is now ready. I will import into GerritHub

**Comment by myitcv** [comment]
This was fixed in [69efc52](https://github.com/cue-lang/cuelang.org/commit/69efc52426b31728daed76c7a096d5648c9001e5)

**Pull request closed without merging**
