### PR TITLE
Hugo: Add missing css variables

### PR DESCRIPTION
**Pull request by JorindeUsMedia**
- Use css variables everywhere so they can be easily overwritten when we want a dark theme
- Use same way of using variables everywhere
- Add missing imports & mixin
- Add defaults for variables in case variables are not set or coming from outside current component
- Change hover state colors of blue button because difference between normal and hover state was too little

For: https://linear.app/usmedia/issue/CUE-130

### CODE REVIEW

**Comment by Lyoness** [comment]
@JorindeUsMedia please can you rebase this one more time?

**Comment by myitcv** [comment]
Thanks @JorindeUsMedia - I definitely don't fully grok all the CSS stuff, but the commit message made it easier to understand what you're up to here!

Importing into Gerrit now.

**Comment by JorindeUsMedia** [comment]
@myitcv Rebased and fixed the conflicts

**Comment by myitcv** [comment]
Closed via ccba4785e030ea701f57658a811bc6723f6f843d

**Pull request closed without merging**
