### PR TITLE
Hugo: Add popup functionality to logos

### PR DESCRIPTION
**Pull request by anne-usmedia**
- Extended the logos__item shortcode to facilitate the popup. From now on, the logos__item shortcode should always be closed.
- Made the logos__item shortcodes on the homepage self closing
- Added dialog typescript for popup functionality. This includes an interface, a base-dialog and a dialog ts
- Added info icon
- Added popup open/close translations eg for screenreaders
- Improved logo styling
- Improved section styling
- Added dialog styling
- Extended the example page and examples with the new attributes (/examples/sections/logos/)

For https://linear.app/usmedia/issue/CUE-259

### CODE REVIEW

**Review by JorindeUsMedia — APPROVED** [review]

**Review by jpluscplusm — CHANGES_REQUESTED** [review]
When I click any 3rd party logo on the homepage, I get taken directly to their site. No popup appears. Not sure how to test this further!

**Review by jpluscplusm — APPROVED** [review]
WFM on https://deploy-preview-414--cue.netlify.app/examples/sections/logos/

**Comment by jpluscplusm** [comment]
Imported as https://review.gerrithub.io/c/cue-lang/cuelang.org/+/1168257

**Comment by myitcv** [comment]
Closed via 15f284192b61eea3f9bcd2ccd25ca39fa4efa99e

**Pull request closed without merging**
