### PR TITLE
Hugo: Added TypeScript and SCSS linters

### PR DESCRIPTION
**Pull request by anne-usmedia**
This includes:
- Installing eslint + config
- Installing stylelint + config
- Adding linter scripts
- Running auto fix lint scripts

For https://linear.app/usmedia/issue/CUE-148

### CODE REVIEW

**Review by JorindeUsMedia — APPROVED** [review]

**Comment by JorindeUsMedia** [comment]
If the linter errors that can't be autofixed aren't that many we can maybe also fix them within this commit?

**Review by Lyoness — APPROVED** [review]
Importing to Gerrit

**Comment by Lyoness** [comment]
https://review.gerrithub.io/c/cue-lang/cuelang.org/+/550647

**Comment by Lyoness** [comment]
Closes [9ec7964](https://github.com/cue-lang/cuelang.org/commit/9ec796417f5ea77c3f7649433fdb7e1595554754) as merged.

**Pull request closed without merging**
