### PR TITLE
Hugo: finetune blog teaser styling (/blog/)

### PR DESCRIPTION
**Pull request by anne-usmedia**
- Moved date above tags
- Made summary text slightly larger so the '...' doesn't fall on the next line
- Cleaned up the list.html
- Cleaned up teaser.scss
- Blog teaser css adjustments - featured images grows with the content hight - remove spacing on the sides - correct font colors

For https://linear.app/usmedia/issue/CUE-325

### CODE REVIEW

**Comment by anne-usmedia** [comment]
FYI, needs a rebase with the search results fixes to see all the fixes

**Review by JorindeUsMedia — APPROVED** [review]

**Review by jpluscplusm — CHANGES_REQUESTED** [review]
> * Moved date above tags ✅ 
> * Made summary text slightly larger so the '...' doesn't fall on the next line ❌ 

I see the "..." on the next line, by itself, on the main blog page: 
image

I guess it's to do with my page width, but if that's the case then isn't this device-dependent?

> * Cleaned up the list.html 🤷 
> * Cleaned up teaser.scss 🤷 
> * Blog teaser css adjustments - featured images grows with the content hight - remove spacing on the sides - correct font colors 🤷

**Comment by anne-usmedia** [comment]
@jpluscplusm yes, it is also depending on page width, and of course the added width of all the characters. I'll adjust the number some more, but it will always be a possibility

**Review by jpluscplusm — APPROVED** [review]
LGTM.

**Comment by jpluscplusm** [comment]
Imported as https://review.gerrithub.io/c/cue-lang/cuelang.org/+/1168307

**Comment by myitcv** [comment]
Closed via d85a288c0e889d0813f986fa79a8d335f25ae81e

**Pull request closed without merging**
