### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by lucendio**
I guess the title says it all.

### CODE REVIEW

**Comment by cedricgc** [comment]
The typo is intentional to show that CUE would throw an error there :)

**Comment by myitcv** [comment]
If you look at the comment to the right of the field name, it's intentionally misspelled.

**Comment by myitcv** [comment]
> The typo is intentional to show that CUE would throw an error there :)

Sorry, just saw this comment! 

Thanks for raising the PR @lucendio, and thanks for the observation @cedricgc !

**Comment by lucendio** [comment]
Oh dear, how embarrassing. I'm so sorry for the noise! Probably too late at night

**Comment by myitcv** [comment]
> Oh dear, how embarrassing. I'm so sorry for the noise! Probably too late at night

Absolutely no need for apologising. One fun little anecdote: in the past someone submitted exactly the same change, and I approved the PR without looking closely enough!

**Comment by lucendio** [comment]
> > Oh dear, how embarrassing. I'm so sorry for the noise! Probably too late at night
> 
> Absolutely no need for apologising. One fun little anecdote: in the past someone submitted exactly the same change, and I approved the PR without looking closely enough!

Fortunately all still humans :)

**Pull request closed without merging**
