### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by chakku000**
fix typo of the example

### CODE REVIEW

**Review by myitcv — APPROVED** [review]
LGTM

**Comment by alexclarke** [comment]
@chakku000 @myitcv  It looks like this was supposed to be misspelled as indicated by the comment
` kind: "Homo Sapiens" // error, misspelled field`

**Comment by myitcv** [comment]
@alexclarke - thank you for catching that. My bad for not reviewing more closely. I will revert this change.

**Comment by myitcv** [comment]
Reverted via https://github.com/cue-lang/cuelang.org/pull/232

**Comment by chakku000** [comment]
Oh, Sorry

**Comment by myitcv** [comment]
@chakku000 no apology required! I should have spotted this during review :)

**Pull request merged**
