### PR TITLE
Playground: Add tabs and make styling same as hugo code-tabs

### PR DESCRIPTION
**Pull request by JorindeUsMedia**
- Create React Tabs component & tab subcomponent
- Tabs-nav logic for showing/hiding pagination (same functionality as hugo tabs-nav but now reactive)
- Create icon component so we can easily use icons from spritesheet in the react app.
- Add base url to env because it's needed for the icon spritesheet which needs absolute url to the main svg
- Handle select tab events and display right content
- Add tabs & tabnav styling (similar to hugo site)
- Move editor scss to separate scss
- Render editors inside of tabs
- Change styling of editor & playground
- Style right editor with 'terminal' styles (blue background)
- Fix font paths for local development playground
- Fix indenting in webpack.config.js

For: https://linear.app/usmedia/issue/CUE-214
and: https://linear.app/usmedia/issue/CUE-219

### CODE REVIEW

**Comment by JorindeUsMedia** [comment]
Discussed with Peter and I'm going to change 2 things before this is ready to merge:
- Change tab titles to Input: [selected input language], Output: [selected output language]
- Change header & tabs colors and backgrounds to improve contrast

**Review by myitcv — APPROVED** [review]
LGTM will import into Gerrit now.

**Review by myitcv — APPROVED** [review]
LGTM will import into Gerrit now.

**Comment by myitcv** [comment]
Closed via baa8844bc9c778184e79d11c5985cae8f4749b25

**Pull request closed without merging**
