### PR TITLE
Hugo: Make anchor keyboard accessible

### PR DESCRIPTION
**Pull request by JorindeUsMedia**
- Add missing import to anchor scss file
- Make sure anchor icon also shows when using the keyboard to navigate the page
- Remove focus style on headings since headings are not focusable so this doesn't do anything

For: https://linear.app/usmedia/issue/CUE-242

### CODE REVIEW

**Comment by myitcv** [comment]
What UI/UX changes should we be reviewing in this PR?

**Comment by myitcv** [comment]
> What UI/UX changes should we be reviewing in this PR?

Ah, I see now.

**Comment by JorindeUsMedia** [comment]
> > What UI/UX changes should we be reviewing in this PR?
> 
> Ah, I see now.

When you use your keyboard to browse docs pages you can see an outline for the anchor links but not the icon so it's not clear where you're focussing on. 

Screenshot from 2023-06-26 09-43-19

**Review by myitcv — APPROVED** [review]
LGTM - will import into GerritHub

**Pull request closed without merging**
