### PR TITLE
Added the sidenote shortcode - for testing: http://localhost:1313/examples/shortcodes/sidenote/

### PR DESCRIPTION
**Pull request by anne-usmedia**
Added the sidenote shortcode - for testing: http://localhost:1313/examples/shortcodes/sidenote/

Includes:
- Created the sidenote shortcode
- Styling of the sidenote
- Added an example page for the sidenote shortcode: /examples/shortcodes/sidenote/

Also edited:
- editorconfig; 'quote_type = single' for scss files so the single quotes do not switch to double quotes when the file is saved

Signed-off-by: Anne van Gorkom <anne.van.gorkom@usmedia.nl>

### CODE REVIEW

**Review by JorindeUsMedia — APPROVED** [review]

**Comment by usm-joost** [comment]
Feedback
- Not so sure if we want to use sidenotes within headers, maybe also allow / style sidenotes outside headers
- I would also add a check within the shortcode if there is text or not (ie. no need to render the sidenote div if there is not text)

**Comment by JorindeUsMedia** [comment]
I've processed @usm-joost feedback.
Test url: https://deploy-preview-296--cue.netlify.app/examples/shortcodes/sidenote/

**Comment by JorindeUsMedia** [comment]
I've processed @usm-joost feedback.
Test url: https://deploy-preview-296--cue.netlify.app/examples/shortcodes/sidenote/

**Comment by myitcv** [comment]
cc @Lyoness

**Review by Lyoness — APPROVED** [review]
LGTM

**Comment by Lyoness** [comment]
@JorindeUsMedia @anne-usmedia 

The `Signed-off-by:` must be the same as the `Author:`  in the commit message, otherwise our DCO check will fail. We're raising a bug on the DCObot upstream and shipping a quick fix so this gets caught in the GitHub PR.

**Review by Lyoness — CHANGES_REQUESTED** [review]
The commit message has a different "signed off by" and email address: 

`Signed-off-by: Jorinde Reijnierse <[anne.van.gorkom@usmedia.nl](mailto:anne.van.gorkom@usmedia.nl)>`

Can you amend this commit to have Anne's name to matches the email address?

**Comment by JorindeUsMedia** [comment]
@Lyoness FIxed the signed-off

**Comment by Lyoness** [comment]
Imported this to Gerrit: https://review.gerrithub.io/c/cue-lang/cuelang.org/+/550249

**Comment by Lyoness** [comment]
closes [1b79444](https://github.com/cue-lang/cuelang.org/commit/1b79444006e33b73421d270cef04d5b2ba6446ee) as merged

**Pull request closed without merging**
